### PR TITLE
Make sure the mountPoint property is public before using it

### PR DESCRIPTION
**Pull request by nickvergessen**
Should fix https://help.nextcloud.com/t/nextcloud-12-0-1-stable-error-cannot-access-private-property/19301/5

Fix https://github.com/nextcloud/server/issues/6171

### CODE REVIEW

**Comment by matt-horwood-mayden** [comment]
I have installed version 1.2.4 and I get the below error!

2017/09/22 11:04:23 [error] 18392#0: *4766 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot access private property OC\Files\Storage\Wrapper\Encryption::$mountPoint in /var/data/websites/3rd_party/horwood_nextcloud/apps/files_accesscontrol/lib/Operation.php on line 85" while reading response header from upstream, client: 81.138.237.78, server: owncloud.horwood.biz, request: "GET /remote.php/webdav/Mortgage/Payslip%20for%20Tax%20Month_5%2C%20Tax%20Year_2017-2018.pdf?downloadStartSecret=m8lobczwwv HTTP/1.1", upstream: "fastcgi://192.168.49.203:9000", host: "owncloud.horwood.biz"

**Comment by nickvergessen** [comment]
Does this patch fix it for you?

**Comment by matt-horwood-mayden** [comment]
Hi @nickvergessen,
Yes that fixes the issue, have added by hand.

**Comment by nickvergessen** [comment]
Rebased to make unit tests pass

**Comment by nickvergessen** [comment]
Released 1.2.5 with this fix

**Pull request merged**
