### PR TITLE
 	Make sure the LoginController is not blocked bei the accesss control

### LINKED ISSUE #5: Error 500 after first login when request is firewalled
### Steps to reproduce
1. Prevent login via rule for non-admins

2. Create new user
3. Try to login
4. See error 500

### Expected behaviour
Should work fine.

### Actual behaviour
Error 500 is displayed:

```
Technical details
Remote Address: 10.211.55.2
Request ID: nKf1b1USbV0d0buVAAe/
Type: OCP\Files\ForbiddenException
Code: 0
Message: Access denied
File: /media/psf/stable9/apps/files_accesscontrol/lib/AccessControl.php
Line: 73

Trace
#0 /media/psf/stable9/apps/files_accesscontrol/lib/AccessControl.php(52): OCA\FilesAccessControl\AccessControl->checkFileAccess(Object(OCA\FilesAccessControl\StorageWrapper), '')
#1 /media/psf/stable9/apps/files_accesscontrol/lib/AppInfo/Application.php(50): OCA\FilesAccessControl\AccessControl->listen(Object(Symfony\Component\EventDispatcher\GenericEvent))
#2 [internal function]: OCA\FilesAccessControl\AppInfo\Application->OCA\FilesAccessControl\AppInfo\{closure}(Object(Symfony\Component\EventDispatcher\GenericEvent), 'OCA\\FilesAccess...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /media/psf/stable9/3rdparty/symfony/event-dispatcher/EventDispatcher.php(181): call_user_func(Object(Closure), Object(Symfony\Component\EventDispatcher\GenericEvent), 'OCA\\FilesAccess...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 /media/psf/stable9/3rdparty/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'OCA\\FilesAccess...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#5 /media/psf/stable9/apps/files_accesscontrol/lib/StorageWrapper.php(49): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('OCA\\FilesAccess...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#6 /media/psf/stable9/apps/files_accesscontrol/lib/StorageWrapper.php(67): OCA\FilesAccessControl\StorageWrapper->emitEvent(Array)
#7 /media/psf/stable9/lib/private/Files/View.php(1120): OCA\FilesAccessControl\StorageWrapper->mkdir('')
#8 /media/psf/stable9/lib/private/Files/View.php(263): OC\Files\View->basicOperation('mkdir', '/test1', Array)
#9 /media/psf/stable9/lib/private/Files/Node/Folder.php(148): OC\Files\View->mkdir('/test1')
#10 /media/psf/stable9/lib/private/Files/Node/Root.php(345): OC\Files\Node\Folder->newFolder('/test1')
#11 /media/psf/stable9/lib/private/Server.php(852): OC\Files\Node\Root->getUserFolder('test1')
#12 /media/psf/stable9/lib/private/User/Session.php(400): OC\Server->getUserFolder('test1')
#13 /media/psf/stable9/lib/private/User/Session.php(455): OC\User\Session->prepareUserLogin()
#14 /media/psf/stable9/lib/private/User/Session.php(291): OC\User\Session->loginWithPassword('test1', 'test1')
#15 /media/psf/stable9/core/Controller/LoginController.php(213): OC\User\Session->login('test1', 'test1')
#16 [internal function]: OC\Core\Controller\LoginController->tryLogin('test1', 'test1', NULL)
#17 /media/psf/stable9/lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array)
#18 /media/psf/stable9/lib/private/AppFramework/Http/Dispatcher.php(90): OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Core\Controller\LoginController), 'tryLogin')
#19 /media/psf/stable9/lib/private/AppFramework/App.php(111): OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Core\Controller\LoginController), 'tryLogin')
#20 /media/psf/stable9/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('LoginController', 'tryLogin', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#21 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#22 /media/psf/stable9/lib/private/Route/Router.php(293): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#23 /media/psf/stable9/lib/base.php(950): OC\Route\Router->match('/login')
#24 /media/psf/stable9/index.php(40): OC::handleRequest()
#25 {main}
```

### LINKED ISSUE #12: File access control breaks theming
Will file more information later.

(@jancborchardt also wonders about avatars)

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Login
- [x] Avatar change
- [x] Theming upload ( #12 )

- [x] Admin page description requires https://github.com/nextcloud/server/pull/750

Fix #5 
Fix #12 

:see_no_evil: @LukasReschke

### CODE REVIEW

**Comment by nickvergessen** [comment]
@schiessle please review

**Comment by schiessle** [comment]
looks good to me :+1:

**Comment by schiessle** [comment]
@LukasReschke also fine with merging this?

**Comment by LukasReschke** [comment]
Let's get this in. 👍

**Comment by LukasReschke** [comment]
@schiessle Do you take care of the backport? 🐱

**Comment by schiessle** [comment]
sure

**Comment by schiessle** [comment]
backport: https://github.com/nextcloud/files_accesscontrol/pull/13

**Pull request merged**
