### PR TITLE
Make Operation work with IEntityCheck

### PR DESCRIPTION
**Pull request by marcelklehr**
This ComplexOperation currently only calls RuleMatcher#setFileInfo (which then calls IFileCheck#setFileInfo), but IFileCheck inherits from IEntityCheck and people implementing a check would thus expect IEntityCheck#setEntitySubject to be called with a Node Object, which however is never called when the flow is triggered by this app, because this app doesn't call RuleMatcher#setEntitySubject. This PR fixes that.

### CODE REVIEW

**Comment by juliushaertl** [comment]
Signoff message is missing ;)

**Comment by marcelklehr** [comment]
damnit. fixed :)

**Review by juliushaertl — APPROVED** [review]

**Comment by nickvergessen** [comment]
I guess you would like to see this backported?

**Pull request merged**
