### PR TITLE
Add hint to settings

### PR DESCRIPTION
**Pull request by jancborchardt**
Adding more hints to settings, ref https://github.com/nextcloud/server/pull/4478 https://github.com/nextcloud/server/pull/4540

Please review @karlitschek @nickvergessen @MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by jancborchardt** [comment]
@nickvergesen I disagree, see https://github.com/nextcloud/server/pull/4540#discussion_r113659454

**Comment by MorrisJobke** [comment]
I could not find where this is added. The little "i" in the admin settings section of access control does only show "open in documentation"

**Comment by jancborchardt** [comment]
@MorrisJobke it needed the server PR to be merged. Update server to master and you will see it there :)
capture du 2017-04-27 20-30-38

**Comment by LukasReschke** [comment]
@jancborchardt Please check the tests before merging code. You broke them. This is bad. Thank you.

**Pull request merged**
