### PR TITLE
Start integration tests

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by juliushaertl** [comment]
@nickvergessen Any objections on getting this in already? Would help to move on with the new cases I've written in #321 to run them individually against the other PRs I've pending.

**Comment by nickvergessen** [comment]
Will do fixup and cs fixing then we can

**Comment by juliushaertl** [comment]
DCO failing from [5c50bfd](https://github.com/nextcloud/files_accesscontrol/pull/317/commits/5c50bfdf86a1eadc480525c6c38c4950bba2764a)

**Review by juliushaertl — APPROVED** [review]
Looks good besides the failing DCO check

**Comment by nickvergessen** [comment]
> Looks good besides the failing DCO check

Right, removed as per commit msg

**Pull request merged**
